# Generated by Django 3.1.1 on 2020-09-25 03:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moniker', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(max_length=20)),
                ('serial_num', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('HOLD', 'Hold'), ('UNAVAILABLE', 'Unavailable'), ('CHECKED_OUT', 'Checked out'), ('LOST', 'Lost')***REMOVED***, default='AVAILABLE', max_length=15)),
                ('date_acquired', models.DateField(blank=True, default=datetime.datetime(2020, 9, 25, 3, 37, 57, 236463, tzinfo=utc))),
                ('last_inspected', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 3, 37, 57, 236495, tzinfo=utc))),
                ('condition', models.CharField(choices=[('BROKEN', 'Broken'), ('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')***REMOVED***, default='FAIR', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equilizer.itemgroup')),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 3, 37, 57, 237336, tzinfo=utc))),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('DENIED', 'Denied')***REMOVED***, default='PENDING', max_length=15)),
                ('checkout_status', models.CharField(choices=[('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost'), ('OUTSTANDING', 'Outstanding')***REMOVED***, default='OUTSTANDING', max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equilizer.item')),
            ***REMOVED***,
        ),
    ***REMOVED***
