# Generated by Django 3.1.1 on 2020-09-23 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equilizer.itemgroup')),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 4, 28, 28, 940178, tzinfo=utc))),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('DENIED', 'Denied')***REMOVED***, default='PENDING', max_length=15)),
                ('checkout_status', models.CharField(choices=[('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost'), ('OUTSTANDING', 'Outstanding')***REMOVED***, default='OUTSTANDING', max_length=15)),
                ('items', models.ManyToManyField(to='equilizer.Item')),
            ***REMOVED***,
        ),
    ***REMOVED***
