# Generated by Django 3.1.1 on 2020-09-25 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equilizer', '0001_initial'),
    ***REMOVED***

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 3, 48, 46, 306151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_acquired',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 25, 3, 48, 46, 305276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_inspected',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 3, 48, 46, 305307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='library_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ***REMOVED***
