# Generated by Django 3.1.1 on 2020-09-23 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equilizer', '0001_initial'),
    ***REMOVED***

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('HOLD', 'Hold'), ('UNAVAILABLE', 'Unavailable'), ('CHECKED_OUT', 'Checked out'), ('LOST', 'Lost')***REMOVED***, default='AVAILABLE', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('BROKEN', 'Broken'), ('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')***REMOVED***, default='FAIR', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='date_acquired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 4, 38, 57, 510933, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='last_inspected',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 4, 38, 57, 510961, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='library_id',
            field=models.CharField(default='CHANGEME', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_num',
            field=models.CharField(default='CHANGEME', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='description',
            field=models.TextField(default='CHANGEME'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='moniker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 4, 38, 57, 511700, tzinfo=utc)),
        ),
    ***REMOVED***
