# Generated by Django 3.1.1 on 2020-09-25 04:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equilizer', '0002_auto_20200925_0348'),
    ***REMOVED***

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 4, 12, 28, 625211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_acquired',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 25, 4, 12, 28, 624215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_inspected',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 4, 12, 28, 624247, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=6, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ***REMOVED***,
        ),
    ***REMOVED***
