# Generated by Django 3.1.1 on 2020-09-25 04:13

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equilizer', '0003_auto_20200925_0412'),
    ***REMOVED***

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 4, 13, 55, 594629, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_acquired',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 25, 4, 13, 55, 593713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_inspected',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 25, 4, 13, 55, 593743, tzinfo=utc)),
        ),
    ***REMOVED***
