# Generated by Django 3.1.1 on 2020-09-28 21:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equilizer', '0005_auto_20200925_2008'),
    ***REMOVED***

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='approver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='approver_id', to='equilizer.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='equilizer.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 28, 21, 47, 20, 467802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_acquired',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 28, 21, 47, 20, 466965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_inspected',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 28, 21, 47, 20, 466993, tzinfo=utc)),
        ),
    ***REMOVED***
